#pragma once

#define SCREENSHOT_PROTOCOL_VERSION 1u

#define IOCTL_SCREENSHOT_QUERY \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_READ_ACCESS)

#define IOCTL_SCREENSHOT_CAPTURE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_OUT_DIRECT, FILE_READ_ACCESS)

#define SCREENSHOT_PIXEL_FORMAT_BGRX8 1u

typedef struct _SCREENSHOT_FRAME_INFO
{
    ULONG Version;
    ULONG Width;
    ULONG Height;
    ULONG SourcePitch;
    ULONG OutputStride;
    ULONG BitsPerPixel;
    ULONG PixelFormat;
    ULONG FrameBytes;
} SCREENSHOT_FRAME_INFO, *PSCREENSHOT_FRAME_INFO;
